<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.12">
  <POU Name="ThisXTS" Id="{adc628a7-7a2e-4111-937d-b66eb159493c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ThisXTS EXTENDS Xts
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="MoverHomeSequence" Id="{dd65f3ed-d01b-4f9f-95cc-8438905256ec}">
      <Declaration><![CDATA[METHOD MoverHomeSequence : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="ThisXTS">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="ThisXTS.MoverHomeSequence">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>