<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="GearCATask_TestSuite" Id="{061b6bca-7336-459c-b0e8-a83117c82ddd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK GearCATask_TestSuite EXTENDS TestSuite<TestSuiteParameter.MaxTestCount>
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>