<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="ResetGroupTast_TestSuite" Id="{caff8344-0c0a-437a-977b-d74e2757ce75}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ResetGroupTast_TestSuite EXTENDS TestSuite<TestSuiteParameter.MaxTestCount>
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>