<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="StopGroupTask_TestSuite" Id="{99aef4ad-4fc7-41c6-a957-800e5b929308}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK StopGroupTask_TestSuite EXTENDS TestSuite<TestSuiteParameter.MaxTestCount>
VAR
	stubCAGroup : I_CollisionGroup;
	testStopGrp : StopMoverGroup:= (MyCollisionGroup := stubCAGroup);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>